language: node_js
node_js:
  - node
before_script:
  - npm install
  - npm test
  - npx webpack --config webpack.config.js
after_success:
notifications:
    slack: wildfirepublicity:Lw0t3aIPsbkmGhdO6TLc9wOA
